stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building application..."

test:
  stage: test
  script:
    - echo "Running tests..."

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
  only:
    - master

include:
  - template: Security/SAST.gitlab-ci.yml